import requests
import os
from tqdm import tqdm

NASA_API_KEY = os.getenv("NASA_API_KEY", "DEMO_KEY")

SOLAR_SYSTEM_DATA = [
    {"name": "Mercury", "type": "Terrestrial", "mass": 0.330, "radius": 2439.7,
     "distance_from_sun": 57.9, "orbital_period": 88.0, "moons": 0,
     "description": "Mercury is the smallest planet in our solar system and closest to the Sun. It has no atmosphere and extreme temperature swings ranging from -180 to 430 degrees Celsius. Mercury completes one orbit around the Sun every 88 Earth days. Its surface is heavily cratered like the Moon. Mercury has a large iron core that makes up about 85% of its radius."},
    {"name": "Venus", "type": "Terrestrial", "mass": 4.867, "radius": 6051.8,
     "distance_from_sun": 108.2, "orbital_period": 224.7, "moons": 0,
     "description": "Venus is the second planet from the Sun and the hottest planet at 465 degrees Celsius due to a thick CO2 atmosphere causing a runaway greenhouse effect. A day on Venus is longer than its year. Venus rotates backwards compared to most planets. Its atmospheric pressure is 92 times that of Earth. Venus has thousands of volcanoes and is covered in thick sulfuric acid clouds."},
    {"name": "Earth", "type": "Terrestrial", "mass": 5.972, "radius": 6371.0,
     "distance_from_sun": 149.6, "orbital_period": 365.25, "moons": 1,
     "description": "Earth is the third planet from the Sun and the only known planet to harbor life. It has a protective magnetic field generated by its iron core, liquid water covering 71% of the surface, and an atmosphere rich in nitrogen and oxygen. Earth has one moon that stabilizes its axial tilt. The planet is 4.5 billion years old and has plate tectonics that constantly reshape its surface."},
    {"name": "Mars", "type": "Terrestrial", "mass": 0.642, "radius": 3389.5,
     "distance_from_sun": 227.9, "orbital_period": 687.0, "moons": 2,
     "description": "Mars is the fourth planet from the Sun known as the Red Planet due to iron oxide on its surface. It has the largest volcano in the solar system, Olympus Mons at 22km high, and the longest canyon system, Valles Marineris at 4000km long. Mars has two small moons: Phobos and Deimos. The Martian day is 24 hours 37 minutes. Mars has seasons like Earth due to its axial tilt. NASA's Perseverance rover is actively searching for signs of ancient life."},
    {"name": "Jupiter", "type": "Gas Giant", "mass": 1898.0, "radius": 69911.0,
     "distance_from_sun": 778.5, "orbital_period": 4331.0, "moons": 95,
     "description": "Jupiter is the fifth planet from the Sun and the largest planet, so massive it could contain all other planets combined. Its Great Red Spot is a storm larger than Earth persisting for over 350 years. Jupiter has at least 95 known moons. The four Galilean moons are Io (most volcanically active body in solar system), Europa (subsurface ocean, prime candidate for life), Ganymede (largest moon in solar system), and Callisto (heavily cratered). Jupiter acts as a shield protecting inner planets from asteroids."},
    {"name": "Saturn", "type": "Gas Giant", "mass": 568.0, "radius": 58232.0,
     "distance_from_sun": 1432.0, "orbital_period": 10747.0, "moons": 146,
     "description": "Saturn is the sixth planet famous for its stunning ring system made of ice and rock particles ranging from tiny grains to boulders as large as a house. It is the least dense planet and could float on water. Saturn has 146 known moons. Titan, its largest moon, has a thick nitrogen atmosphere and lakes of liquid methane and ethane. Enceladus has geysers of water ice erupting from its south pole, suggesting a subsurface ocean."},
    {"name": "Uranus", "type": "Ice Giant", "mass": 86.8, "radius": 25362.0,
     "distance_from_sun": 2867.0, "orbital_period": 30589.0, "moons": 28,
     "description": "Uranus is the seventh planet and rotates on its side with an axial tilt of 98 degrees, likely caused by a massive collision billions of years ago. It is an ice giant composed of water, methane, and ammonia ices. The methane in its atmosphere absorbs red light giving Uranus its distinctive blue-green color. Its rings were discovered in 1977. Uranus has 28 known moons all named after Shakespeare characters."},
    {"name": "Neptune", "type": "Ice Giant", "mass": 102.0, "radius": 24622.0,
     "distance_from_sun": 4515.0, "orbital_period": 59800.0, "moons": 16,
     "description": "Neptune is the eighth and farthest planet with the strongest winds in the solar system reaching 2100 km/h. It has a large storm called the Great Dark Spot. Neptune was predicted mathematically before being observed. Its largest moon Triton orbits backwards suggesting it was captured from the Kuiper Belt. Neptune takes 165 Earth years to orbit the Sun and has only completed one orbit since its discovery in 1846."},
]

NASA_MISSIONS_DATA = [
    {"name": "James Webb Space Telescope", "launch_date": "2021-12-25", "status": "Active",
     "target": "Deep Space / Early Universe", "agency": "NASA/ESA/CSA",
     "description": "The James Webb Space Telescope is the most powerful space telescope ever built, observing in infrared light. It can see the first galaxies formed 200 million years after the Big Bang, peer into dusty stellar nurseries where stars are born, and analyze the atmospheres of exoplanets for biosignatures. JWST operates at -233 degrees Celsius at Lagrange Point 2, 1.5 million km from Earth."},
    {"name": "Perseverance Rover", "launch_date": "2020-07-30", "status": "Active",
     "target": "Mars - Jezero Crater", "agency": "NASA",
     "description": "NASA's Perseverance rover landed on Mars in February 2021 in Jezero Crater, an ancient lake bed. It is searching for signs of ancient microbial life, collecting 43 rock and soil samples sealed in titanium tubes for future return to Earth. Perseverance carries the Ingenuity helicopter which made the first powered flight on another planet. MOXIE successfully produced oxygen from the Martian atmosphere."},
    {"name": "Artemis Program", "launch_date": "2022-11-16", "status": "Active",
     "target": "Moon - Lunar South Pole", "agency": "NASA",
     "description": "The Artemis program aims to return humans to the Moon for the first time since Apollo 17 in 1972, including the first woman and first person of color. Artemis I completed an uncrewed test flight around the Moon in 2022. Artemis II will carry astronauts around the Moon. Artemis III will land astronauts near the lunar south pole where water ice exists in permanently shadowed craters."},
    {"name": "Voyager 1", "launch_date": "1977-09-05", "status": "Active",
     "target": "Interstellar Space", "agency": "NASA",
     "description": "Voyager 1 is the farthest human-made object, now over 23 billion kilometers from Earth in interstellar space beyond the heliopause. Launched in 1977, it flew past Jupiter in 1979 and Saturn in 1980. It still transmits data to Earth with signals taking over 22 hours each way. Voyager 1 carries the Golden Record containing sounds and images representing life on Earth."},
    {"name": "Hubble Space Telescope", "launch_date": "1990-04-24", "status": "Active",
     "target": "Various / Deep Field", "agency": "NASA/ESA",
     "description": "The Hubble Space Telescope has transformed astronomy for over 30 years. It helped determine the universe is 13.8 billion years old, discovered dark energy is accelerating the expansion of the universe, observed the birth and death of stars, and photographed galaxies billions of light years away in the Hubble Deep Field images. Hubble has made over 1.5 million observations."},
    {"name": "Cassini-Huygens", "launch_date": "1997-10-15", "status": "Completed",
     "target": "Saturn System", "agency": "NASA/ESA/ASI",
     "description": "Cassini orbited Saturn for 13 years studying its rings, atmosphere, magnetosphere and moons. It discovered active geysers on Enceladus indicating a subsurface liquid water ocean with hydrothermal vents, making it a top candidate for life. The Huygens probe landed on Titan in 2005. Cassini ended with the Grand Finale diving into Saturn's atmosphere in 2017."},
    {"name": "New Horizons", "launch_date": "2006-01-19", "status": "Active",
     "target": "Pluto / Kuiper Belt", "agency": "NASA",
     "description": "New Horizons performed the historic first flyby of Pluto in July 2015 at 14 km/s, revealing a geologically active world with 3500m water ice mountains, a vast nitrogen plain called Tombaugh Regio, a hazy atmosphere, and possible subsurface ocean. It then flew past Arrokoth, a Kuiper Belt contact binary, in 2019. New Horizons continues into the outer solar system."},
    {"name": "Parker Solar Probe", "launch_date": "2018-08-12", "status": "Active",
     "target": "Sun / Solar Corona", "agency": "NASA",
     "description": "Parker Solar Probe is humanity's closest approach to the Sun, flying through the solar corona and surviving temperatures of 1400 degrees Celsius with its revolutionary heat shield. It has broken records for closest approach and fastest human-made object. Parker is studying solar wind origin, magnetic field structure, and energetic particle acceleration to help predict space weather that affects Earth."},
]

DEEP_SPACE_KNOWLEDGE = [
    {"content": "Black Holes: What They Are\nA black hole is a region of spacetime where gravity is so strong that nothing, not even light, can escape once past the event horizon. Black holes form when massive stars collapse at the end of their lives in supernova explosions. The boundary of a black hole is called the event horizon. At the center is a singularity where density becomes infinite and our laws of physics break down. Supermassive black holes exist at the center of most galaxies including our own Milky Way, called Sagittarius A*, which has a mass of 4 million suns.", "source": "Deep Space: Black Holes", "type": "deep_space"},
    {"content": "Neutron Stars and Pulsars\nNeutron stars are the collapsed cores of massive stars that exploded as supernovae. They are incredibly dense: a teaspoon of neutron star material weighs about 10 million tonnes. Neutron stars are about 20 km in diameter but contain more mass than the Sun. Pulsars are rotating neutron stars that emit beams of electromagnetic radiation. Some pulsars rotate hundreds of times per second called millisecond pulsars. When two neutron stars merge they produce gravitational waves and a kilonova explosion that creates heavy elements like gold and platinum.", "source": "Deep Space: Neutron Stars", "type": "deep_space"},
    {"content": "Galaxies: Types and Structure\nGalaxies are massive systems of stars, gas, dust, and dark matter held together by gravity. There are three main types: spiral galaxies like the Milky Way with pinwheel arms, elliptical galaxies which are smooth and featureless, and irregular galaxies with no defined shape. The Milky Way contains 100-400 billion stars and is 100,000 light years across. The nearest large galaxy is Andromeda, 2.5 million light years away, which is on a collision course with the Milky Way in 4.5 billion years. The observable universe contains an estimated 2 trillion galaxies.", "source": "Deep Space: Galaxies", "type": "deep_space"},
    {"content": "Dark Matter and Dark Energy\nDark matter is invisible matter that does not interact with light but exerts gravitational force. It makes up 27% of the universe and holds galaxies together — without it, galaxies would fly apart. Scientists detect dark matter through its gravitational effects on visible matter and light bending called gravitational lensing. Dark energy is even more mysterious, making up 68% of the universe. It is a property of space itself that drives the accelerating expansion of the universe. Only 5% of the universe is ordinary matter we can see and detect.", "source": "Deep Space: Dark Matter and Dark Energy", "type": "deep_space"},
    {"content": "The Big Bang and Universe Origin\nThe universe began approximately 13.8 billion years ago in an event called the Big Bang — not an explosion in space but an expansion of space itself from an infinitely hot and dense state. Within the first second, fundamental particles formed. After 380,000 years, atoms formed and the universe became transparent — this light is still visible today as the Cosmic Microwave Background radiation. The first stars formed about 200 million years after the Big Bang. The universe continues to expand and that expansion is accelerating due to dark energy.", "source": "Deep Space: Big Bang Theory", "type": "deep_space"},
    {"content": "Exoplanets: Planets Beyond Our Solar System\nExoplanets are planets orbiting stars other than our Sun. Over 5,500 exoplanets have been confirmed as of 2024. They are detected by the transit method (planet passing in front of its star dims the starlight), radial velocity (planet's gravity wobbles the star), and direct imaging. The habitable zone or Goldilocks zone is the range of distances from a star where liquid water could exist on a planet's surface. Notable exoplanets include Kepler-452b (Earth's cousin), TRAPPIST-1 system with 7 Earth-sized planets including 3 in the habitable zone, and Proxima Centauri b orbiting our nearest star.", "source": "Deep Space: Exoplanets", "type": "deep_space"},
    {"content": "Stars: Life Cycle and Types\nStars form in nebulae — clouds of gas and dust — when gravity causes the material to collapse and heat up until nuclear fusion ignites. Stars spend most of their lives on the main sequence fusing hydrogen into helium. Our Sun is a medium-sized yellow dwarf star 4.6 billion years old with another 5 billion years remaining. Massive stars live fast and die young in supernova explosions. Star types by temperature from hottest to coolest: O (blue), B (blue-white), A (white), F (yellow-white), G (yellow, our Sun), K (orange), M (red dwarfs, most common stars). Red dwarfs can live for trillions of years.", "source": "Deep Space: Stellar Evolution", "type": "deep_space"},
    {"content": "Supernovae and Stellar Death\nA supernova is an enormous stellar explosion that can briefly outshine an entire galaxy of 100 billion stars. Type II supernovae occur when massive stars (over 8 solar masses) exhaust their fuel and their cores collapse in milliseconds. Type Ia supernovae occur in binary systems when a white dwarf accretes mass and explodes. Supernovae create and distribute heavy elements — every atom of gold, silver, and uranium in your body was forged in a stellar explosion. The energy released in a supernova is greater than the Sun will emit in its entire 10 billion year lifetime.", "source": "Deep Space: Supernovae", "type": "deep_space"},
    {"content": "Gravitational Waves\nGravitational waves are ripples in the fabric of spacetime caused by accelerating massive objects, predicted by Einstein's general relativity in 1915 and first directly detected by LIGO in September 2015. The first detection came from two black holes 1.3 billion light years away merging together. Gravitational waves travel at the speed of light. LIGO detectors can measure spacetime distortions smaller than one thousandth the diameter of a proton. Gravitational wave astronomy has opened a new window to observe the universe including black hole and neutron star mergers that produce gold and other heavy elements.", "source": "Deep Space: Gravitational Waves", "type": "deep_space"},
    {"content": "The Milky Way Galaxy\nThe Milky Way is our home galaxy, a barred spiral galaxy approximately 100,000 light years in diameter containing 100-400 billion stars. The Sun is located in the Orion Arm about 26,000 light years from the galactic center. The galactic center hosts Sagittarius A*, a supermassive black hole with 4 million solar masses. The Milky Way takes 225-250 million years to complete one rotation called a galactic year. The Milky Way has several satellite dwarf galaxies including the Large and Small Magellanic Clouds visible from the southern hemisphere.", "source": "Deep Space: Milky Way Galaxy", "type": "deep_space"},
    {"content": "Space-Time and General Relativity\nEinstein's theory of general relativity describes gravity not as a force but as a curvature of spacetime caused by mass and energy. Massive objects like stars and black holes warp spacetime around them and other objects follow these curves. This explains why light bends around massive objects — gravitational lensing. General relativity predicts time dilation: time passes more slowly in stronger gravitational fields and at higher velocities. GPS satellites must account for general and special relativistic effects or navigation would drift by kilometers per day. Black holes are the most extreme prediction of general relativity.", "source": "Deep Space: General Relativity", "type": "deep_space"},
    {"content": "Dimensions and String Theory\nString theory proposes that the fundamental constituents of the universe are not point particles but tiny one-dimensional vibrating strings of energy. Different vibration modes produce different particles. String theory requires 10 or 11 dimensions — beyond our familiar 3 spatial dimensions and 1 time dimension. The extra dimensions are thought to be compactified or curled up at the Planck scale, far too small to observe. M-theory unifies five versions of string theory and requires 11 dimensions. These extra dimensions could explain why gravity is so much weaker than other fundamental forces.", "source": "Deep Space: Dimensions and String Theory", "type": "deep_space"},
    {"content": "Time Dilation and Space Travel\nTime dilation is a real, measured phenomenon where time passes at different rates depending on velocity and gravity. At 99% the speed of light, time passes about 7 times slower than for a stationary observer. Astronauts on the International Space Station age slightly slower due to their velocity but slightly faster due to weaker gravity, resulting in aging about 0.007 seconds less per 6-month mission. For a hypothetical journey to the nearest star Proxima Centauri at 99.9% light speed, travelers would experience only 4.3 years while over 60 years pass on Earth. This is not science fiction but proven physics.", "source": "Deep Space: Time Dilation", "type": "deep_space"},
    {"content": "Nebulae: Stellar Nurseries and Graveyards\nNebulae are vast clouds of gas and dust in space. Emission nebulae glow from ionized gas energized by nearby hot stars — the Orion Nebula is a famous example where stars are actively forming 1,344 light years away. Planetary nebulae are shells of gas ejected by dying Sun-like stars — the beautiful Ring Nebula and Cat's Eye Nebula are examples. Supernova remnants like the Crab Nebula are expanding shells from stellar explosions. Dark nebulae are so dense they block light from stars behind them. Nebulae are the raw material from which new stars and planetary systems form.", "source": "Deep Space: Nebulae", "type": "deep_space"},
    {"content": "The Search for Extraterrestrial Life (SETI)\nThe search for extraterrestrial life encompasses multiple approaches. The Drake Equation estimates the number of communicating civilizations in the Milky Way considering factors like star formation rate, fraction with planets, and probability of life developing. The Fermi Paradox asks why, given the high probability of life, we have found no evidence — proposed solutions include the Great Filter theory. Scientists look for biosignatures in exoplanet atmospheres like oxygen, methane, or phosphine. Enceladus and Europa are prime candidates for microbial life in their subsurface oceans. The TRAPPIST-1 system is intensively studied with JWST.", "source": "Deep Space: Search for Life", "type": "deep_space"},
    {"content": "Cosmic Scale and Distances\nThe universe operates on scales almost incomprehensible to the human mind. A light year is the distance light travels in one year — about 9.46 trillion kilometers. The nearest star Proxima Centauri is 4.24 light years away. The Milky Way is 100,000 light years across. The Andromeda galaxy is 2.5 million light years away. The observable universe is 93 billion light years in diameter (because space has expanded since the Big Bang). If the Sun were the size of a basketball, Earth would be a sesame seed 26 meters away, and Proxima Centauri would be another basketball 7,000 km away.", "source": "Deep Space: Cosmic Scale", "type": "deep_space"},
    {"content": "Quantum Mechanics and the Universe\nQuantum mechanics describes the behavior of matter and energy at the smallest scales. At the quantum level, particles exist in superposition — multiple states simultaneously — until observed. Quantum entanglement allows particles to be correlated instantaneously across any distance, which Einstein called spooky action at a distance. The Heisenberg Uncertainty Principle states you cannot simultaneously know both position and momentum of a particle precisely. Quantum fluctuations in the early universe seeded the density variations that grew into galaxies and large-scale structure. Reconciling quantum mechanics with general relativity is the greatest unsolved problem in physics.", "source": "Deep Space: Quantum Mechanics", "type": "deep_space"},
    {"content": "Asteroids, Comets, and the Kuiper Belt\nAsteroids are rocky bodies mostly found in the asteroid belt between Mars and Jupiter. The dwarf planet Ceres is the largest asteroid belt object. Near-Earth asteroids are monitored for potential impact risk. Comets are icy bodies from the outer solar system that develop spectacular tails when heated by the Sun — dust tail pushed by radiation pressure and ion tail blown by solar wind. The Kuiper Belt extends from Neptune's orbit to 50 AU containing Pluto, Eris, and billions of icy objects. The Oort Cloud is a theoretical spherical shell of comets extending to 100,000 AU, representing the outermost boundary of the solar system.", "source": "Deep Space: Asteroids and Comets", "type": "deep_space"},
    {"content": "Solar Physics: Our Star\nThe Sun is a G-type main sequence star 1.39 million km in diameter containing 99.86% of the solar system's mass. At its core, 600 million tonnes of hydrogen fuse into helium every second releasing energy via E=mc². Energy takes about 100,000 years to travel from the core to the surface through radiative and convective zones. The solar corona — outer atmosphere — reaches over 1 million degrees Celsius, far hotter than the surface at 5,500 degrees — the coronal heating problem remains unsolved. Solar flares and coronal mass ejections can disrupt Earth's magnetic field, power grids, and satellites. The solar wind streams charged particles throughout the solar system at 400-800 km/s.", "source": "Deep Space: Solar Physics", "type": "deep_space"},
    {"content": "The Multiverse Theory\nThe multiverse is the hypothetical set of all possible universes including our own. Multiple independent theories suggest its existence. Eternal inflation theory proposes our Big Bang was one of many bubble universes forming continuously in an eternally inflating space. The many-worlds interpretation of quantum mechanics suggests every quantum event spawns parallel universes. String theory's landscape contains 10^500 possible vacuum states each potentially a different universe with different physical constants. If the multiverse exists, there could be universes with different values of fundamental constants, different numbers of dimensions, or radically different physics. The multiverse remains speculative but scientifically motivated.", "source": "Deep Space: Multiverse Theory", "type": "deep_space"},
    {"content": "International Space Station\nThe International Space Station is a modular space station in low Earth orbit at approximately 400 km altitude, traveling at 7.66 km/s and completing 15.5 orbits per day. It has been continuously inhabited since November 2000. The ISS is a joint project of NASA, Roscosmos, ESA, JAXA, and CSA. It is 109 meters wide and has a pressurized volume of 916 cubic meters. Astronauts conduct experiments in microgravity studying biology, physics, astronomy, and human physiology. The ISS experiences 16 sunrises and sunsets per day. Without constant orbital boosts, atmospheric drag would cause it to deorbit within years.", "source": "Space Stations: ISS", "type": "station"},
    {"content": "SpaceX and Commercial Space\nSpaceX founded by Elon Musk in 2002 has revolutionized spaceflight with reusable rockets. The Falcon 9 first stage booster lands propulsively and has been reused over 20 times. Falcon Heavy is currently the world's most powerful operational rocket. Dragon spacecraft carries crew and cargo to the ISS. Starship is the largest rocket ever built designed for missions to Moon and Mars using full and rapid reusability. SpaceX Starlink constellation provides global satellite internet. SpaceX has reduced launch costs by over 10 times compared to previous methods, democratizing access to space.", "source": "Commercial Space: SpaceX", "type": "commercial"},
    {"content": "Wormholes and Theoretical Physics\nWormholes, or Einstein-Rosen bridges, are hypothetical tunnels through spacetime connecting distant regions of the universe or even different universes. They are valid mathematical solutions to Einstein's field equations. A traversable wormhole would require exotic matter with negative energy density to hold it open — no known material has this property. If wormholes exist and could be stabilized, they would theoretically allow faster-than-light travel or even time travel. Physicist Kip Thorne showed wormholes could in principle be traversable. Stephen Hawking proposed the chronology protection conjecture suggesting nature prevents paradoxes by making wormholes unstable.", "source": "Theoretical Physics: Wormholes", "type": "theoretical"},
]

SPACE_FACTS = [
    "The Sun contains 99.86% of all the mass in the solar system.",
    "A neutron star is so dense that a teaspoon of its material would weigh about 10 million tonnes.",
    "The Milky Way galaxy contains an estimated 100 to 400 billion stars.",
    "Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.",
    "The universe is approximately 13.8 billion years old.",
    "Black holes are regions where gravity is so strong that nothing, not even light, can escape past the event horizon.",
    "The International Space Station orbits Earth at approximately 28,000 km/h completing 15.5 orbits daily.",
    "There are more stars in the observable universe than grains of sand on all of Earth's beaches.",
    "The Great Red Spot on Jupiter is a storm that has been continuously active for over 350 years.",
    "Water ice has been confirmed in permanently shadowed craters near the lunar south pole.",
    "Olympus Mons on Mars is the tallest volcano in the solar system at 22 km high and 600 km wide.",
    "Europa, moon of Jupiter, likely has twice as much liquid water as all Earth's oceans beneath its ice shell.",
    "The temperature at the core of the Sun is approximately 15 million degrees Celsius.",
    "Saturn's rings are made mostly of water ice particles and would span most of the distance from Earth to Moon.",
    "A day on Venus is longer than a year on Venus — it takes 243 Earth days to rotate but only 225 days to orbit the Sun.",
    "The Voyager 1 spacecraft has traveled over 23 billion kilometers and is in interstellar space beyond our solar system.",
    "Gravitational waves were first directly detected by LIGO in September 2015 from two merging black holes 1.3 billion light years away.",
    "The observable universe is about 93 billion light years in diameter even though it is only 13.8 billion years old due to cosmic expansion.",
    "Time passes more slowly in stronger gravitational fields — a clock at Earth's core runs slightly slower than one at sea level.",
    "The Andromeda Galaxy is on a collision course with the Milky Way and they will merge in approximately 4.5 billion years.",
    "At the speed of light, it would take 100,000 years to cross the Milky Way galaxy.",
    "The first image of a black hole event horizon was captured in 2019 by the Event Horizon Telescope — it was the M87 galaxy's black hole 6.5 billion times the mass of the Sun.",
    "Sgr A*, the supermassive black hole at the center of the Milky Way, was imaged in 2022 and has a mass of 4 million Suns.",
    "TRAPPIST-1 system has 7 Earth-sized planets with 3 in the habitable zone, making it a prime target in the search for life.",
    "The speed of light is approximately 299,792 km/s — nothing with mass can reach this speed.",
    "Gold and other heavy elements on Earth were created in neutron star mergers billions of years ago.",
    "The cosmic microwave background radiation is the afterglow of the Big Bang still visible today across the entire sky.",
    "Quantum entanglement allows particles to be correlated instantaneously regardless of the distance between them.",
    "The James Webb Space Telescope can detect the heat signature of a bumblebee at the distance of the Moon.",
    "Pluto was reclassified as a dwarf planet in 2006. It has a heart-shaped nitrogen ice plain called Tombaugh Regio.",
]

def fetch_apod(api_key="DEMO_KEY"):
    try:
        url = f"https://api.nasa.gov/planetary/apod?api_key={api_key}&count=10"
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            return response.json()
        return []
    except Exception as e:
        print(f"NASA API unavailable: {e}")
        return []

def load_planets_to_db(db_session):
    from app.models.database import Planet
    for planet_data in tqdm(SOLAR_SYSTEM_DATA, desc="Loading planets"):
        existing = db_session.query(Planet).filter(Planet.name == planet_data["name"]).first()
        if not existing:
            planet = Planet(**planet_data)
            db_session.add(planet)
    db_session.commit()
    print(f"Loaded {len(SOLAR_SYSTEM_DATA)} planets into database.")

def load_missions_to_db(db_session):
    from app.models.database import NasaMission
    for mission_data in tqdm(NASA_MISSIONS_DATA, desc="Loading missions"):
        existing = db_session.query(NasaMission).filter(NasaMission.name == mission_data["name"]).first()
        if not existing:
            mission = NasaMission(**mission_data)
            db_session.add(mission)
    db_session.commit()
    print(f"Loaded {len(NASA_MISSIONS_DATA)} missions into database.")

def get_all_documents():
    documents = []
    for p in SOLAR_SYSTEM_DATA:
        doc = f"Planet: {p['name']}\nType: {p['type']}\nMass: {p['mass']} x 10^24 kg\nRadius: {p['radius']} km\nDistance from Sun: {p['distance_from_sun']} million km\nOrbital Period: {p['orbital_period']} Earth days\nMoons: {p['moons']}\nDescription: {p['description']}"
        documents.append({"content": doc, "source": f"Planet: {p['name']}", "type": "planet"})
    for m in NASA_MISSIONS_DATA:
        doc = f"Mission: {m['name']}\nAgency: {m['agency']}\nLaunch Date: {m['launch_date']}\nStatus: {m['status']}\nTarget: {m['target']}\nDescription: {m['description']}"
        documents.append({"content": doc, "source": f"Mission: {m['name']}", "type": "mission"})
    for item in DEEP_SPACE_KNOWLEDGE:
        documents.append(item)
    for i, fact in enumerate(SPACE_FACTS):
        documents.append({"content": f"Space Fact #{i+1}: {fact}", "source": f"Space Facts #{i+1}", "type": "fact"})
    print(f"Prepared {len(documents)} documents for RAG pipeline.")
    return documents